export let SC_GOAL_REQUEST = 'SC_GOAL_REQUEST'
export let SC_GOAL_FAILED = 'SC_GOAL_FAILED'
export let SC_GOAL_SUCCESS = 'SC_GOAL_SUCCESS'

export let GET_SC_GOAL_REQUEST = 'GET_SC_GOAL_REQUEST'
export let GET_SC_GOAL_SUCCESS = 'GET_SC_GOAL_SUCCESS'
export let GET_SC_GOAL_FAILED = 'GET_SC_GOAL_FAILED'

export let SC_NEXT_STEP_REQUEST = 'SC_NEXT_STEP_REQUEST'
export let SC_NEXT_STEP_SUCCESS = 'SC_NEXT_STEP_SUCCESS'
export let SC_NEXT_STEP_FAILED = 'SC_NEXT_STEP_FAILED'
export let GET_NEXT_STEP_GOAL_REQUEST = 'GET_NEXT_STEP_GOAL_REQUEST'
export let GET_NEXT_STEP_GOAL_SUCCESS = 'GET_NEXT_STEP_GOAL_SUCCESS'
export let GET_NEXT_STEP_GOAL_FAILED = 'GET_NEXT_STEP_GOAL_FAILED'

export let PROFILE_REQUEST = 'PROFILE_REQUEST'
export let PROFILE_SUCCESS = 'PROFILE_SUCCESS'
export let PROFILE_FAILED = 'PROFILE_FAILED'

export let API_FAILURE = 'API_FAILURE'

export let GET_ACHIEVEMENT_LEVELS_REQUEST = 'GET_ACHIEVEMENT_LEVELS_REQUEST'
export let GET_ACHIEVEMENT_LEVELS_SUCCESS = 'GET_ACHIEVEMENT_LEVELS_SUCCESS'
export let GET_ACHIEVEMENT_LEVELS_FAILED = 'GET_ACHIEVEMENT_LEVELS_FAILED'

export let GET_BONUS_REQUEST = 'GET_BONUS_REQUEST'
export let GET_BONUS_SUCCESS = 'GET_BONUS_SUCCESS'
export let GET_BONUS_FAILED = 'GET_BONUS_FAILED'

export let GET_ADDITIONAL_LEVELS_REQUEST = 'GET_ADDITIONAL_LEVELS_REQUEST'
export let GET_ADDITIONAL_LEVELS_SUCCESS = 'GET_ADDITIONAL_LEVELS_SUCCESS'
export let GET_ADDITIONAL_LEVELS_FAILED = 'GET_ADDITIONAL_LEVELS_FAILED'

export let GET_TEAM_MEMBERS_REQUEST = 'GET_TEAM_MEMBERS_REQUEST'
export let GET_TEAM_MEMBERS_SUCCESS = 'GET_TEAM_MEMBERS_SUCCESS'
export let GET_TEAM_MEMBERS_FAILED = 'GET_TEAM_MEMBERS_FAILED'

export let GET_EHC_MEMBER_REQUEST = 'GET_EHC_MEMBER_REQUEST'
export let GET_EHC_MEMBER_SUCCESS = 'GET_EHC_MEMBER_SUCCESS'
export let GET_EHC_MEMBER_FAILED = 'GET_EHC_MEMBER_FAILED'

export let GET_MEMBER_COMMITMENT_REQUEST = 'GET_MEMBER_COMMITMENT_REQUEST'
export let GET_MEMBER_COMMITMENT_SUCCESS = 'GET_MEMBER_COMMITMENT_SUCCESS'
export let GET_MEMBER_COMMITMENT_FAILED = 'GET_MEMBER_COMMITMENT_FAILED'

export let GET_SPONSOR_LIST_REQUEST = 'GET_SPONSOR_LIST_REQUEST'
export let GET_SPONSOR_LIST_SUCCESS = 'GET_SPONSOR_LIST_SUCCESS'
export let GET_SPONSOR_LIST_FAILED = 'GET_SPONSOR_LIST_FAILED'

export let GET_WEEKLY_ACTIONS_REQUEST = 'GET_WEEKLY_ACTIONS_REQUEST'
export let GET_WEEKLY_ACTIONS_SUCCESS = 'GET_WEEKLY_ACTIONS_SUCCESS'
export let GET_WEEKLY_ACTIONS_FAILED = 'GET_WEEKLY_ACTIONS_FAILED'
